stages:
  dataset_baseline:
    cmd : python src/dataset_baseline.py
    deps:
      - data/raw/NYC.csv
      - src/dataset_baseline.py
      - src/feature_definitions.py
    outs:
      - data/processed/baseline/processed_NYC.csv

  features_baseline:
    cmd : python src/features_baseline.py
    deps :
      - data/processed/baseline/processed_NYC.csv
      - src/features_baseline.py
    params :
      - features_baseline.test_size
      - features_baseline.random_state
    outs :
      - data/processed/baseline/features.csv
      - data/processed/baseline/labels.csv
      - data/processed/baseline/features_test.csv
      - data/processed/baseline/labels_test.csv

  dataset_osrm:
    cmd : python src/dataset_osrm.py
    deps:
      - data/raw/NYC.csv
      - data/external/osrm_data.csv
      - src/dataset_osrm.py
    outs:
      - data/processed/osrm_boosted/processed_osrm_NYC.csv

  features_osrm:
    cmd : python src/features_osrm.py
    deps :
      - data/processed/osrm_boosted/processed_osrm_NYC.csv
      - src/features_osrm.py
    params :
      - features_osrm.test_size
      - features_osrm.random_state
    outs :
      - data/processed/osrm_boosted/features.csv
      - data/processed/osrm_boosted/labels.csv
      - data/processed/osrm_boosted/features_test.csv
      - data/processed/osrm_boosted/labels_test.csv

  Model_Training:
    cmd : python src/modeling/train.py
    deps :
      - data/processed/osrm_boosted/features.csv
      - data/processed/osrm_boosted/labels.csv
      - src/modeling/train.py
    params: 
      - Train.LightGBM
      - Train.XGBOOST
    outs:
      - models/model.joblib
    
  Model_Evaluating:
    cmd : python src/modeling/predict.py
    deps:
      - data/processed/osrm_boosted/features.csv
      - data/processed/osrm_boosted/labels.csv
      - data/processed/osrm_boosted/features_test.csv
      - data/processed/osrm_boosted/labels_test.csv
      - models/model.joblib
    outs:
      - data/processed/test_predictions.csv
      - reports/evaluation_metrics.json
      - run_information.json
